### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by baimafeima** [rgrannell1/polonium#4]
Could you make a new release here on GitHub? Is this project still maintained? If no, what application are you currently using? Could you also make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by rgrannell1** [comment]
Hi, this software is maintained but I'd recommend you try LessPass, it's a newer and more active project. I have a changelog in News.md, I can add them to the release notes in future. This project was stagnant / feature complete for 2 years, I am currently updating it to separate its core lib from its cli, to add browser support to the lib.

**Comment by rgrannell1** [comment]
Also, just to check, do you use this software? Or is this just a general note?

**Comment by baimafeima** [comment]
@rgrannell1 Thanks for the feedback and the recommendations. This is just a general note but I am looking for the currently best stateless password manager.
